"""
MIDI Prep — Generate a MIDI reference file from a song cover.

Used in **beginner mode** to create the note sequence that the CV system
will use for rhythm-only playback (user strums, notes come from the MIDI).

Wraps the existing pipeline:
    YouTube download → stem separation → Basic Pitch → MIDI

Usage:
    from app.midi_prep import prepare_midi

    midi_path = prepare_midi(
        song_url="https://youtube.com/watch?v=...",
        instrument_name="nylon_guitar",
    )
"""

from __future__ import annotations

import os
import sys
import time

# ── Path setup ───────────────────────────────────────────────────────────
REPO_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_MIDI_SF_DIR = os.path.join(REPO_DIR, "MIDI_TO_SOUNDFONT")
_MIDI_GEN_DIR = os.path.join(_MIDI_SF_DIR, "MIDI_generation")
_PLAYER_DIR = os.path.join(_MIDI_SF_DIR, "FluidSynth_Player")

for _d in (_MIDI_SF_DIR, _MIDI_GEN_DIR, _PLAYER_DIR):
    if _d not in sys.path:
        sys.path.insert(0, _d)

from youtube_to_midi import download_audio, is_youtube_url, search_youtube
from generate_MIDI import audio_to_midi
from stem_separator import separate_stems, get_best_stem, pick_stem_for_instrument

# Default output directory for MIDI files generated by the app
MIDI_OUTPUT_DIR = os.path.join(REPO_DIR, "app", "midi_output")


# ═══════════════════════════════════════════════════════════════════════
#  STEP FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════

def step_download_audio(song_url: str, output_dir: str | None = None) -> str:
    """
    Download audio from a YouTube URL.

    Returns:
        str: Path to the downloaded WAV file.
    """
    if output_dir is None:
        output_dir = MIDI_OUTPUT_DIR
    os.makedirs(output_dir, exist_ok=True)

    print()
    print("─" * 55)
    print("  Step 1: Download Audio")
    print("─" * 55)

    return download_audio(song_url, output_dir)


def step_separate_stems(
    audio_path: str,
    instrument_name: str,
    use_six_stems: bool = False,
) -> str:
    """
    Separate audio into stems and pick the best one for the instrument.

    Returns:
        str: Path to the isolated stem audio file.
    """
    print()
    print("─" * 55)
    print("  Step 2: Separate Stems")
    print("─" * 55)

    target_stem = pick_stem_for_instrument(instrument_name, use_six_stems)
    needs_six = target_stem in ("guitar", "piano")
    if needs_six and not use_six_stems:
        print(f"  '{instrument_name}' → '{target_stem}' — using 6-stem model")
        use_six_stems = True

    stems = separate_stems(audio_path=audio_path, use_six_stems=use_six_stems)
    stem_name, stem_path = get_best_stem(stems, instrument_name, use_six_stems)
    print(f"  Selected stem: '{stem_name}' → {os.path.basename(stem_path)}")
    return stem_path


def step_convert_to_midi(audio_path: str, output_dir: str | None = None) -> str:
    """
    Convert an audio file (or stem) to MIDI using Basic Pitch.

    Returns:
        str: Path to the generated MIDI file.
    """
    if output_dir is None:
        output_dir = MIDI_OUTPUT_DIR
    os.makedirs(output_dir, exist_ok=True)

    print()
    print("─" * 55)
    print("  Step 3: Convert to MIDI")
    print("─" * 55)

    return audio_to_midi(audio_path, output_dir=output_dir)


# ═══════════════════════════════════════════════════════════════════════
#  MAIN: PREPARE MIDI
# ═══════════════════════════════════════════════════════════════════════

def prepare_midi(
    song_url: str,
    instrument_name: str = "nylon_guitar",
    separate: bool = True,
    six_stems: bool = False,
    output_dir: str | None = None,
    keep_audio: bool = True,
) -> tuple[str, str | None]:
    """
    Full pipeline: download a song cover → separate stems → convert to MIDI.

    This is used in **beginner mode** to create the note reference that the
    CV system plays back when the user strums.

    Args:
        song_url:        YouTube URL of the song cover.
        instrument_name: GM instrument name (e.g. "nylon_guitar") for stem selection.
        separate:        Whether to run stem separation (recommended).
        six_stems:       Use the 6-stem Demucs model (slower, better guitar/piano isolation).
        output_dir:      Where to save output files.
        keep_audio:      Whether to keep the downloaded audio file.

    Returns:
        tuple: (midi_path, audio_path)
            - midi_path: Path to the generated .mid file
            - audio_path: Path to the downloaded audio (or None if not kept)
    """
    if output_dir is None:
        output_dir = MIDI_OUTPUT_DIR

    start = time.time()

    print()
    print("╔" + "═" * 55 + "╗")
    print("║  MIDI Preparation (Beginner Mode)                  ║")
    print("╠" + "═" * 55 + "╣")
    print(f"║  URL:        {song_url[:42]:<42} ║")
    print(f"║  Instrument: {instrument_name[:42]:<42} ║")
    print(f"║  Stems:      {'6-stem' if six_stems else '4-stem' if separate else 'off':<42} ║")
    print("╚" + "═" * 55 + "╝")

    # Step 1: Download audio
    audio_path = step_download_audio(song_url, output_dir)

    # Step 2: Separate stems (optional but recommended)
    if separate:
        audio_for_midi = step_separate_stems(audio_path, instrument_name, six_stems)
    else:
        audio_for_midi = audio_path
        print("\n  [Stem separation skipped]")

    # Step 3: Convert to MIDI
    midi_path = step_convert_to_midi(audio_for_midi, output_dir)

    elapsed = time.time() - start
    print()
    print(f"  MIDI ready in {elapsed:.1f}s: {os.path.basename(midi_path)}")

    final_audio = audio_path if keep_audio else None
    return midi_path, final_audio


def prepare_midi_from_file(
    audio_path: str,
    instrument_name: str = "nylon_guitar",
    separate: bool = True,
    six_stems: bool = False,
    output_dir: str | None = None,
) -> str:
    """
    Convert a local audio file to MIDI (no download step).

    Returns:
        str: Path to the generated MIDI file.
    """
    if output_dir is None:
        output_dir = MIDI_OUTPUT_DIR

    print()
    print("╔" + "═" * 55 + "╗")
    print("║  MIDI Preparation (from local file)                ║")
    print("╚" + "═" * 55 + "╝")

    if separate:
        audio_for_midi = step_separate_stems(audio_path, instrument_name, six_stems)
    else:
        audio_for_midi = audio_path

    return step_convert_to_midi(audio_for_midi, output_dir)
