import type {
  Instrument,
  Song,
  RemixStyle,
  Remix,
  PerformanceResult,
  Persona,
  Instructor,
} from "./types"

export const instruments: Instrument[] = [
  {
    id: "guitar",
    name: "Guitar",
    icon: "Guitar",
    color: "#FF9600",
    description: "Acoustic or electric, strum your way through any genre",
    difficulty: "beginner",
    origin: "Worldwide",
  },
  {
    id: "piano",
    name: "Piano",
    icon: "Piano",
    color: "#1CB0F6",
    description: "The foundation of Western music, keys to everything",
    difficulty: "beginner",
    origin: "Italy",
  },
  {
    id: "violin",
    name: "Violin",
    icon: "Music",
    color: "#CE82FF",
    description: "Elegant strings that sing with emotion and precision",
    difficulty: "intermediate",
    origin: "Italy",
  },
  {
    id: "drums",
    name: "Drums",
    icon: "Drum",
    color: "#FF4B4B",
    description: "Keep the beat, drive the rhythm, feel the pulse",
    difficulty: "beginner",
    origin: "Worldwide",
  },
  {
    id: "flute",
    name: "Flute",
    icon: "Wind",
    color: "#58CC02",
    description: "Breathy tones that float above any ensemble",
    difficulty: "intermediate",
    origin: "Worldwide",
  },
  {
    id: "trumpet",
    name: "Trumpet",
    icon: "Megaphone",
    color: "#FFC800",
    description: "Bold brass that commands attention in any arrangement",
    difficulty: "advanced",
    origin: "Worldwide",
  },
  {
    id: "sitar",
    name: "Sitar",
    icon: "Waves",
    color: "#FF9600",
    description: "The soul of Indian classical music, rich with resonance",
    difficulty: "advanced",
    origin: "India",
  },
  {
    id: "erhu",
    name: "Erhu",
    icon: "Music2",
    color: "#FF4B4B",
    description: "Two-stringed Chinese fiddle with a haunting voice",
    difficulty: "advanced",
    origin: "China",
  },
]

export const songs: Song[] = [
  {
    id: "twinkle",
    title: "Twinkle Twinkle Little Star",
    artist: "Traditional",
    genre: "Classical",
    difficulty: "beginner",
    duration: 60,
    bpm: 80,
    key: "C Major",
    instrumentIds: ["piano", "guitar", "flute", "violin"],
  },
  {
    id: "fur-elise",
    title: "Fur Elise",
    artist: "Beethoven",
    genre: "Classical",
    difficulty: "intermediate",
    duration: 180,
    bpm: 70,
    key: "A Minor",
    instrumentIds: ["piano", "guitar"],
  },
  {
    id: "yesterday",
    title: "Yesterday",
    artist: "The Beatles",
    genre: "Pop",
    difficulty: "beginner",
    duration: 125,
    bpm: 97,
    key: "F Major",
    instrumentIds: ["guitar", "piano"],
  },
  {
    id: "take-five",
    title: "Take Five",
    artist: "Dave Brubeck",
    genre: "Jazz",
    difficulty: "advanced",
    duration: 324,
    bpm: 174,
    key: "Eb Minor",
    instrumentIds: ["piano", "drums", "trumpet"],
  },
  {
    id: "canon-d",
    title: "Canon in D",
    artist: "Johann Pachelbel",
    genre: "Classical",
    difficulty: "intermediate",
    duration: 300,
    bpm: 60,
    key: "D Major",
    instrumentIds: ["piano", "violin", "guitar"],
  },
  {
    id: "moonlight",
    title: "Moonlight Sonata",
    artist: "Beethoven",
    genre: "Classical",
    difficulty: "intermediate",
    duration: 360,
    bpm: 56,
    key: "C# Minor",
    instrumentIds: ["piano"],
  },
  {
    id: "bohemian",
    title: "Bohemian Rhapsody",
    artist: "Queen",
    genre: "Rock",
    difficulty: "advanced",
    duration: 354,
    bpm: 72,
    key: "Bb Major",
    instrumentIds: ["guitar", "piano", "drums"],
  },
  {
    id: "autumn-leaves",
    title: "Autumn Leaves",
    artist: "Joseph Kosma",
    genre: "Jazz",
    difficulty: "intermediate",
    duration: 200,
    bpm: 120,
    key: "G Minor",
    instrumentIds: ["piano", "guitar", "trumpet"],
  },
  {
    id: "ode-to-joy",
    title: "Ode to Joy",
    artist: "Beethoven",
    genre: "Classical",
    difficulty: "beginner",
    duration: 90,
    bpm: 108,
    key: "D Major",
    instrumentIds: ["piano", "guitar", "flute", "violin"],
  },
  {
    id: "stairway",
    title: "Stairway to Heaven",
    artist: "Led Zeppelin",
    genre: "Rock",
    difficulty: "advanced",
    duration: 480,
    bpm: 82,
    key: "A Minor",
    instrumentIds: ["guitar"],
  },
  // Extended catalog — many more songs for Pick & Play
  { id: "happy-birthday", title: "Happy Birthday", artist: "Traditional", genre: "Pop", difficulty: "beginner", duration: 20, bpm: 100, key: "C Major", instrumentIds: ["piano", "guitar", "flute"] },
  { id: "jingle-bells", title: "Jingle Bells", artist: "Traditional", genre: "Holiday", difficulty: "beginner", duration: 90, bpm: 120, key: "G Major", instrumentIds: ["piano", "guitar", "violin", "flute"] },
  { id: "ode-to-joy-full", title: "Ode to Joy (Full)", artist: "Beethoven", genre: "Classical", difficulty: "intermediate", duration: 180, bpm: 108, key: "D Major", instrumentIds: ["piano", "guitar", "violin", "flute"] },
  { id: "greensleeves", title: "Greensleeves", artist: "Traditional", genre: "Folk", difficulty: "intermediate", duration: 120, bpm: 60, key: "A Minor", instrumentIds: ["guitar", "piano", "violin"] },
  { id: "amazing-grace", title: "Amazing Grace", artist: "Traditional", genre: "Gospel", difficulty: "beginner", duration: 90, bpm: 72, key: "G Major", instrumentIds: ["piano", "guitar", "flute"] },
  { id: "house-of-rising-sun", title: "House of the Rising Sun", artist: "The Animals", genre: "Rock", difficulty: "intermediate", duration: 260, bpm: 88, key: "A Minor", instrumentIds: ["guitar", "piano"] },
  { id: "wonderwall", title: "Wonderwall", artist: "Oasis", genre: "Rock", difficulty: "beginner", duration: 258, bpm: 87, key: "Em", instrumentIds: ["guitar", "piano"] },
  { id: "let-it-be", title: "Let It Be", artist: "The Beatles", genre: "Pop", difficulty: "beginner", duration: 243, bpm: 72, key: "C Major", instrumentIds: ["piano", "guitar"] },
  { id: "hey-jude", title: "Hey Jude", artist: "The Beatles", genre: "Pop", difficulty: "intermediate", duration: 431, bpm: 72, key: "F Major", instrumentIds: ["piano", "guitar"] },
  { id: "clocks", title: "Clocks", artist: "Coldplay", genre: "Pop", difficulty: "intermediate", duration: 307, bpm: 132, key: "Eb Major", instrumentIds: ["piano", "guitar"] },
  { id: "all-of-me", title: "All of Me", artist: "John Legend", genre: "Pop", difficulty: "intermediate", duration: 269, bpm: 72, key: "Ab Major", instrumentIds: ["piano", "guitar"] },
  { id: "summertime", title: "Summertime", artist: "Gershwin", genre: "Jazz", difficulty: "advanced", duration: 180, bpm: 80, key: "A Minor", instrumentIds: ["piano", "trumpet", "violin"] },
  { id: "fly-me-to-moon", title: "Fly Me to the Moon", artist: "Frank Sinatra", genre: "Jazz", difficulty: "intermediate", duration: 145, bpm: 112, key: "C Major", instrumentIds: ["piano", "guitar", "trumpet"] },
  { id: "blue-bossa", title: "Blue Bossa", artist: "Kenny Dorham", genre: "Jazz", difficulty: "intermediate", duration: 240, bpm: 176, key: "C Minor", instrumentIds: ["piano", "trumpet", "guitar"] },
  { id: "so-what", title: "So What", artist: "Miles Davis", genre: "Jazz", difficulty: "advanced", duration: 320, bpm: 88, key: "D Minor", instrumentIds: ["trumpet", "piano", "drums"] },
  { id: "giant-steps", title: "Giant Steps", artist: "John Coltrane", genre: "Jazz", difficulty: "advanced", duration: 290, bpm: 144, key: "Bb Major", instrumentIds: ["piano", "trumpet"] },
  { id: "prelude-c-bach", title: "Prelude in C Major", artist: "J.S. Bach", genre: "Classical", difficulty: "intermediate", duration: 156, bpm: 72, key: "C Major", instrumentIds: ["piano", "guitar"] },
  { id: "minuet-g", title: "Minuet in G", artist: "J.S. Bach", genre: "Classical", difficulty: "beginner", duration: 90, bpm: 96, key: "G Major", instrumentIds: ["piano", "violin"] },
  { id: "clair-de-lune", title: "Clair de Lune", artist: "Debussy", genre: "Classical", difficulty: "advanced", duration: 300, bpm: 52, key: "Db Major", instrumentIds: ["piano"] },
  { id: "nocturne-op9", title: "Nocturne Op. 9 No. 2", artist: "Chopin", genre: "Classical", difficulty: "advanced", duration: 270, bpm: 69, key: "Eb Major", instrumentIds: ["piano"] },
  { id: "rondo-alla-turca", title: "Rondo Alla Turca", artist: "Mozart", genre: "Classical", difficulty: "advanced", duration: 210, bpm: 116, key: "A Minor", instrumentIds: ["piano"] },
  { id: "symphony-5", title: "Symphony No. 5 (Theme)", artist: "Beethoven", genre: "Classical", difficulty: "intermediate", duration: 60, bpm: 108, key: "C Minor", instrumentIds: ["piano", "violin", "flute"] },
  { id: "canon-pachelbel-short", title: "Canon in D (Excerpt)", artist: "Pachelbel", genre: "Classical", difficulty: "beginner", duration: 120, bpm: 54, key: "D Major", instrumentIds: ["piano", "violin", "guitar"] },
  { id: "river-flows", title: "River Flows in You", artist: "Yiruma", genre: "Contemporary", difficulty: "intermediate", duration: 216, bpm: 72, key: "A Minor", instrumentIds: ["piano"] },
  { id: "comptine-dun-autre", title: "Comptine d'un autre été", artist: "Yann Tiersen", genre: "Contemporary", difficulty: "intermediate", duration: 132, bpm: 100, key: "E Minor", instrumentIds: ["piano"] },
  { id: "nothing-else-matters", title: "Nothing Else Matters", artist: "Metallica", genre: "Rock", difficulty: "intermediate", duration: 388, bpm: 52, key: "Em", instrumentIds: ["guitar", "piano"] },
  { id: "wish-you-were-here", title: "Wish You Were Here", artist: "Pink Floyd", genre: "Rock", difficulty: "intermediate", duration: 334, bpm: 76, key: "G Major", instrumentIds: ["guitar", "piano"] },
  { id: "sweet-child", title: "Sweet Child O' Mine", artist: "Guns N' Roses", genre: "Rock", difficulty: "advanced", duration: 356, bpm: 126, key: "D Major", instrumentIds: ["guitar"] },
  { id: "hotel-california", title: "Hotel California", artist: "Eagles", genre: "Rock", difficulty: "advanced", duration: 391, bpm: 76, key: "B Minor", instrumentIds: ["guitar", "piano"] },
  { id: "blackbird", title: "Blackbird", artist: "The Beatles", genre: "Rock", difficulty: "intermediate", duration: 138, bpm: 94, key: "G Major", instrumentIds: ["guitar"] },
  { id: "dust-in-wind", title: "Dust in the Wind", artist: "Kansas", genre: "Rock", difficulty: "intermediate", duration: 203, bpm: 88, key: "C Major", instrumentIds: ["guitar", "violin"] },
  { id: "stand-by-me", title: "Stand by Me", artist: "Ben E. King", genre: "Soul", difficulty: "beginner", duration: 178, bpm: 72, key: "A Major", instrumentIds: ["guitar", "piano"] },
  { id: "what-a-wonderful-world", title: "What a Wonderful World", artist: "Louis Armstrong", genre: "Jazz", difficulty: "beginner", duration: 139, bpm: 72, key: "F Major", instrumentIds: ["trumpet", "piano", "guitar"] },
  { id: "my-favorite-things", title: "My Favorite Things", artist: "Rodgers & Hammerstein", genre: "Jazz", difficulty: "intermediate", duration: 180, bpm: 120, key: "Eb Major", instrumentIds: ["piano", "violin"] },
  { id: "ave-maria", title: "Ave Maria", artist: "Schubert", genre: "Classical", difficulty: "advanced", duration: 360, bpm: 52, key: "Bb Major", instrumentIds: ["piano", "violin", "flute"] },
  { id: "brahms-lullaby", title: "Brahms' Lullaby", artist: "Brahms", genre: "Classical", difficulty: "beginner", duration: 90, bpm: 72, key: "Eb Major", instrumentIds: ["piano", "guitar", "violin"] },
  { id: "vivaldi-spring", title: "Spring (Four Seasons)", artist: "Vivaldi", genre: "Classical", difficulty: "intermediate", duration: 600, bpm: 120, key: "E Major", instrumentIds: ["violin", "piano"] },
  { id: "sakura", title: "Sakura (Cherry Blossoms)", artist: "Traditional Japanese", genre: "Traditional", difficulty: "beginner", duration: 90, bpm: 80, key: "D Major", instrumentIds: ["flute", "piano", "guitar"] },
  { id: "scales-and-arpeggios", title: "Scales and Arpeggios", artist: "Disney", genre: "Pop", difficulty: "beginner", duration: 90, bpm: 100, key: "C Major", instrumentIds: ["piano", "flute"] },
  { id: "hallelujah", title: "Hallelujah", artist: "Leonard Cohen", genre: "Pop", difficulty: "intermediate", duration: 252, bpm: 72, key: "C Major", instrumentIds: ["guitar", "piano"] },
  { id: "imagine", title: "Imagine", artist: "John Lennon", genre: "Pop", difficulty: "beginner", duration: 183, bpm: 76, key: "C Major", instrumentIds: ["piano", "guitar"] },
  { id: "lean-on-me", title: "Lean on Me", artist: "Bill Withers", genre: "Soul", difficulty: "beginner", duration: 243, bpm: 88, key: "C Major", instrumentIds: ["piano", "guitar"] },
  { id: "superstition", title: "Superstition", artist: "Stevie Wonder", genre: "Funk", difficulty: "advanced", duration: 267, bpm: 96, key: "Eb Minor", instrumentIds: ["piano", "drums", "trumpet"] },
  { id: "billie-jean", title: "Billie Jean", artist: "Michael Jackson", genre: "Pop", difficulty: "intermediate", duration: 294, bpm: 117, key: "F# Minor", instrumentIds: ["piano", "drums", "guitar"] },
  { id: "seven-nation-army", title: "Seven Nation Army", artist: "The White Stripes", genre: "Rock", difficulty: "beginner", duration: 231, bpm: 124, key: "E Minor", instrumentIds: ["guitar", "drums"] },
  { id: "smells-like-teen-spirit", title: "Smells Like Teen Spirit", artist: "Nirvana", genre: "Rock", difficulty: "intermediate", duration: 301, bpm: 117, key: "F Minor", instrumentIds: ["guitar", "drums"] },
  { id: "back-in-black", title: "Back in Black", artist: "AC/DC", genre: "Rock", difficulty: "intermediate", duration: 255, bpm: 96, key: "E Minor", instrumentIds: ["guitar", "drums"] },
  { id: "we-will-rock-you", title: "We Will Rock You", artist: "Queen", genre: "Rock", difficulty: "beginner", duration: 122, bpm: 84, key: "Bb Major", instrumentIds: ["drums", "guitar", "piano"] },
  { id: "eye-of-tiger", title: "Eye of the Tiger", artist: "Survivor", genre: "Rock", difficulty: "intermediate", duration: 263, bpm: 109, key: "C Minor", instrumentIds: ["guitar", "drums"] },
  { id: "mission-impossible", title: "Mission Impossible Theme", artist: "Lalo Schifrin", genre: "Film", difficulty: "advanced", duration: 120, bpm: 140, key: "E Minor", instrumentIds: ["trumpet", "piano"] },
  { id: "james-bond", title: "James Bond Theme", artist: "Monty Norman", genre: "Film", difficulty: "intermediate", duration: 108, bpm: 120, key: "E Minor", instrumentIds: ["guitar", "trumpet"] },
  // Extended bank — well-known songs for a large built-in catalog
  { id: "let-it-be", title: "Let It Be", artist: "The Beatles", genre: "Rock", difficulty: "beginner", duration: 243, bpm: 72, key: "C Major", instrumentIds: ["piano", "guitar"] },
  { id: "hey-jude", title: "Hey Jude", artist: "The Beatles", genre: "Rock", difficulty: "intermediate", duration: 431, bpm: 72, key: "F Major", instrumentIds: ["piano", "guitar"] },
  { id: "come-together", title: "Come Together", artist: "The Beatles", genre: "Rock", difficulty: "intermediate", duration: 259, bpm: 83, key: "E Minor", instrumentIds: ["guitar", "drums"] },
  { id: "someone-like-you", title: "Someone Like You", artist: "Adele", genre: "Pop", difficulty: "intermediate", duration: 285, bpm: 68, key: "A Major", instrumentIds: ["piano", "guitar"] },
  { id: "rolling-in-deep", title: "Rolling in the Deep", artist: "Adele", genre: "Pop", difficulty: "intermediate", duration: 228, bpm: 105, key: "C Minor", instrumentIds: ["piano", "drums"] },
  { id: "hello-adele", title: "Hello", artist: "Adele", genre: "Pop", difficulty: "intermediate", duration: 295, bpm: 79, key: "F Minor", instrumentIds: ["piano"] },
  { id: "shape-of-you", title: "Shape of You", artist: "Ed Sheeran", genre: "Pop", difficulty: "intermediate", duration: 234, bpm: 96, key: "C# Minor", instrumentIds: ["guitar", "piano"] },
  { id: "thinking-out-loud", title: "Thinking Out Loud", artist: "Ed Sheeran", genre: "Pop", difficulty: "beginner", duration: 281, bpm: 79, key: "D Major", instrumentIds: ["guitar", "piano"] },
  { id: "perfect", title: "Perfect", artist: "Ed Sheeran", genre: "Pop", difficulty: "beginner", duration: 263, bpm: 96, key: "G Major", instrumentIds: ["guitar", "piano"] },
  { id: "shake-it-off", title: "Shake It Off", artist: "Taylor Swift", genre: "Pop", difficulty: "beginner", duration: 219, bpm: 160, key: "C Major", instrumentIds: ["piano", "guitar"] },
  { id: "love-story", title: "Love Story", artist: "Taylor Swift", genre: "Pop", difficulty: "beginner", duration: 236, bpm: 120, key: "C Major", instrumentIds: ["guitar", "piano"] },
  { id: "blank-space", title: "Blank Space", artist: "Taylor Swift", genre: "Pop", difficulty: "intermediate", duration: 231, bpm: 96, key: "C Major", instrumentIds: ["piano"] },
  { id: "piano-man", title: "Piano Man", artist: "Billy Joel", genre: "Rock", difficulty: "intermediate", duration: 339, bpm: 88, key: "C Major", instrumentIds: ["piano", "guitar"] },
  { id: "uptown-girl", title: "Uptown Girl", artist: "Billy Joel", genre: "Pop", difficulty: "intermediate", duration: 198, bpm: 128, key: "C Major", instrumentIds: ["piano"] },
  { id: "your-song", title: "Your Song", artist: "Elton John", genre: "Pop", difficulty: "beginner", duration: 241, bpm: 72, key: "Eb Major", instrumentIds: ["piano", "guitar"] },
  { id: "rocket-man", title: "Rocket Man", artist: "Elton John", genre: "Rock", difficulty: "intermediate", duration: 295, bpm: 72, key: "B Major", instrumentIds: ["piano", "guitar"] },
  { id: "tiny-dancer", title: "Tiny Dancer", artist: "Elton John", genre: "Rock", difficulty: "intermediate", duration: 374, bpm: 84, key: "C Major", instrumentIds: ["piano", "guitar"] },
  { id: "purple-rain", title: "Purple Rain", artist: "Prince", genre: "Rock", difficulty: "advanced", duration: 506, bpm: 72, key: "Bb Major", instrumentIds: ["guitar", "piano"] },
  { id: "when-doves-cry", title: "When Doves Cry", artist: "Prince", genre: "Pop", difficulty: "intermediate", duration: 234, bpm: 120, key: "A Minor", instrumentIds: ["piano", "guitar"] },
  { id: "thriller", title: "Thriller", artist: "Michael Jackson", genre: "Pop", difficulty: "advanced", duration: 357, bpm: 119, key: "C# Minor", instrumentIds: ["piano", "drums"] },
  { id: "smooth-criminal", title: "Smooth Criminal", artist: "Michael Jackson", genre: "Pop", difficulty: "advanced", duration: 258, bpm: 118, key: "B Minor", instrumentIds: ["piano", "drums"] },
  { id: "beat-it", title: "Beat It", artist: "Michael Jackson", genre: "Rock", difficulty: "intermediate", duration: 258, bpm: 138, key: "Eb Minor", instrumentIds: ["guitar", "drums"] },
  { id: "sweet-home-alabama", title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd", genre: "Rock", difficulty: "intermediate", duration: 284, bpm: 96, key: "D Major", instrumentIds: ["guitar", "piano"] },
  { id: "free-bird", title: "Free Bird", artist: "Lynyrd Skynyrd", genre: "Rock", difficulty: "advanced", duration: 539, bpm: 84, key: "G Major", instrumentIds: ["guitar"] },
  { id: "comfortably-numb", title: "Comfortably Numb", artist: "Pink Floyd", genre: "Rock", difficulty: "advanced", duration: 383, bpm: 80, key: "B Minor", instrumentIds: ["guitar", "piano"] },
  { id: "another-brick", title: "Another Brick in the Wall Pt. 2", artist: "Pink Floyd", genre: "Rock", difficulty: "intermediate", duration: 238, bpm: 96, key: "D Minor", instrumentIds: ["guitar", "drums"] },
  { id: "money", title: "Money", artist: "Pink Floyd", genre: "Rock", difficulty: "advanced", duration: 382, bpm: 126, key: "Bb Major", instrumentIds: ["guitar", "drums"] },
  { id: "kashmir", title: "Kashmir", artist: "Led Zeppelin", genre: "Rock", difficulty: "advanced", duration: 508, bpm: 84, key: "D Minor", instrumentIds: ["guitar", "drums"] },
  { id: "black-dog", title: "Black Dog", artist: "Led Zeppelin", genre: "Rock", difficulty: "advanced", duration: 296, bpm: 82, key: "A Major", instrumentIds: ["guitar", "drums"] },
  { id: "rock-and-roll", title: "Rock and Roll", artist: "Led Zeppelin", genre: "Rock", difficulty: "intermediate", duration: 220, bpm: 174, key: "A Major", instrumentIds: ["guitar", "drums"] },
  { id: "dreams", title: "Dreams", artist: "Fleetwood Mac", genre: "Rock", difficulty: "intermediate", duration: 257, bpm: 120, key: "F Major", instrumentIds: ["guitar", "piano"] },
  { id: "go-your-own-way", title: "Go Your Own Way", artist: "Fleetwood Mac", genre: "Rock", difficulty: "intermediate", duration: 218, bpm: 126, key: "A Major", instrumentIds: ["guitar", "drums"] },
  { id: "landslide", title: "Landslide", artist: "Fleetwood Mac", genre: "Rock", difficulty: "beginner", duration: 199, bpm: 84, key: "C Major", instrumentIds: ["guitar", "piano"] },
  { id: "don't-stop", title: "Don't Stop", artist: "Fleetwood Mac", genre: "Rock", difficulty: "intermediate", duration: 193, bpm: 120, key: "E Major", instrumentIds: ["piano", "guitar"] },
  { id: "creep", title: "Creep", artist: "Radiohead", genre: "Rock", difficulty: "intermediate", duration: 238, bpm: 92, key: "G Major", instrumentIds: ["guitar", "piano"] },
  { id: "karma-police", title: "Karma Police", artist: "Radiohead", genre: "Rock", difficulty: "intermediate", duration: 262, bpm: 74, key: "F# Minor", instrumentIds: ["piano", "guitar"] },
  { id: "no-surprises", title: "No Surprises", artist: "Radiohead", genre: "Rock", difficulty: "beginner", duration: 229, bpm: 72, key: "F Major", instrumentIds: ["piano", "guitar"] },
  { id: "zombie", title: "Zombie", artist: "The Cranberries", genre: "Rock", difficulty: "intermediate", duration: 312, bpm: 84, key: "E Minor", instrumentIds: ["guitar"] },
  { id: "linger", title: "Linger", artist: "The Cranberries", genre: "Rock", difficulty: "intermediate", duration: 276, bpm: 88, key: "C Major", instrumentIds: ["guitar", "piano"] },
  { id: "wonderwall", title: "Wonderwall", artist: "Oasis", genre: "Rock", difficulty: "beginner", duration: 258, bpm: 87, key: "Em", instrumentIds: ["guitar"] },
  { id: "don't-look-back", title: "Don't Look Back in Anger", artist: "Oasis", genre: "Rock", difficulty: "intermediate", duration: 291, bpm: 88, key: "C Major", instrumentIds: ["guitar", "piano"] },
  { id: "yellow", title: "Yellow", artist: "Coldplay", genre: "Rock", difficulty: "beginner", duration: 266, bpm: 88, key: "Bb Major", instrumentIds: ["guitar", "piano"] },
  { id: "fix-you", title: "Fix You", artist: "Coldplay", genre: "Rock", difficulty: "intermediate", duration: 295, bpm: 72, key: "C Major", instrumentIds: ["piano", "guitar"] },
  { id: "clocks", title: "Clocks", artist: "Coldplay", genre: "Rock", difficulty: "intermediate", duration: 307, bpm: 131, key: "Eb Major", instrumentIds: ["piano", "drums"] },
  { id: "viva-la-vida", title: "Viva la Vida", artist: "Coldplay", genre: "Rock", difficulty: "intermediate", duration: 242, bpm: 138, key: "C Major", instrumentIds: ["piano", "guitar"] },
  { id: "blinding-lights", title: "Blinding Lights", artist: "The Weeknd", genre: "Pop", difficulty: "intermediate", duration: 200, bpm: 171, key: "D Minor", instrumentIds: ["piano", "drums"] },
  { id: "starboy", title: "Starboy", artist: "The Weeknd", genre: "Pop", difficulty: "intermediate", duration: 230, bpm: 186, key: "Ab Minor", instrumentIds: ["piano", "drums"] },
  { id: "levitating", title: "Levitating", artist: "Dua Lipa", genre: "Pop", difficulty: "intermediate", duration: 203, bpm: 103, key: "Bb Minor", instrumentIds: ["piano", "drums"] },
  { id: "don't-start-now", title: "Don't Start Now", artist: "Dua Lipa", genre: "Pop", difficulty: "intermediate", duration: 183, bpm: 124, key: "Bb Minor", instrumentIds: ["piano"] },
  { id: "bad-guy", title: "bad guy", artist: "Billie Eilish", genre: "Pop", difficulty: "intermediate", duration: 194, bpm: 135, key: "G Minor", instrumentIds: ["piano", "guitar"] },
  { id: "when-the-party-over", title: "when the party's over", artist: "Billie Eilish", genre: "Pop", difficulty: "intermediate", duration: 196, bpm: 84, key: "D Minor", instrumentIds: ["piano"] },
  { id: "everything-i-wanted", title: "everything i wanted", artist: "Billie Eilish", genre: "Pop", difficulty: "intermediate", duration: 244, bpm: 120, key: "F# Minor", instrumentIds: ["piano"] },
  { id: "uptown-funk", title: "Uptown Funk", artist: "Bruno Mars", genre: "Funk", difficulty: "intermediate", duration: 269, bpm: 115, key: "D Minor", instrumentIds: ["piano", "drums"] },
  { id: "just-the-way", title: "Just the Way You Are", artist: "Bruno Mars", genre: "Pop", difficulty: "beginner", duration: 219, bpm: 109, key: "D Major", instrumentIds: ["piano", "guitar"] },
  { id: "grenade", title: "Grenade", artist: "Bruno Mars", genre: "Pop", difficulty: "intermediate", duration: 223, bpm: 108, key: "D Minor", instrumentIds: ["piano"] },
  { id: "single-ladies", title: "Single Ladies", artist: "Beyoncé", genre: "Pop", difficulty: "intermediate", duration: 192, bpm: 96, key: "D Minor", instrumentIds: ["piano", "drums"] },
  { id: "halo", title: "Halo", artist: "Beyoncé", genre: "Pop", difficulty: "intermediate", duration: 222, bpm: 92, key: "Eb Major", instrumentIds: ["piano"] },
  { id: "crazy-in-love", title: "Crazy in Love", artist: "Beyoncé", genre: "Pop", difficulty: "intermediate", duration: 235, bpm: 99, key: "C Major", instrumentIds: ["piano", "drums"] },
  { id: "chopsticks", title: "Chopsticks", artist: "Traditional", genre: "Classical", difficulty: "beginner", duration: 60, bpm: 120, key: "C Major", instrumentIds: ["piano"] },
  { id: "ode-to-joy-easy", title: "Ode to Joy (Easy)", artist: "Beethoven", genre: "Classical", difficulty: "beginner", duration: 60, bpm: 108, key: "D Major", instrumentIds: ["piano", "flute", "violin"] },
  { id: "minuet-g", title: "Minuet in G", artist: "Bach", genre: "Classical", difficulty: "beginner", duration: 90, bpm: 96, key: "G Major", instrumentIds: ["piano", "violin"] },
  { id: "prelude-c", title: "Prelude in C Major", artist: "Bach", genre: "Classical", difficulty: "intermediate", duration: 156, bpm: 54, key: "C Major", instrumentIds: ["piano"] },
  { id: "air-on-g-string", title: "Air on the G String", artist: "Bach", genre: "Classical", difficulty: "intermediate", duration: 320, bpm: 54, key: "D Major", instrumentIds: ["violin", "piano"] },
  { id: "moonlight-sonata-1", title: "Moonlight Sonata (1st mvmt)", artist: "Beethoven", genre: "Classical", difficulty: "intermediate", duration: 330, bpm: 52, key: "C# Minor", instrumentIds: ["piano"] },
  { id: "fur-elise-easy", title: "Für Elise (Simplified)", artist: "Beethoven", genre: "Classical", difficulty: "beginner", duration: 90, bpm: 70, key: "A Minor", instrumentIds: ["piano"] },
  { id: "all-of-me", title: "All of Me", artist: "John Legend", genre: "Pop", difficulty: "intermediate", duration: 269, bpm: 72, key: "Ab Major", instrumentIds: ["piano", "guitar"] },
  { id: "say-something", title: "Say Something", artist: "A Great Big World", genre: "Pop", difficulty: "beginner", duration: 229, bpm: 72, key: "C Major", instrumentIds: ["piano"] },
  { id: "all-i-want", title: "All I Want", artist: "Kodaline", genre: "Rock", difficulty: "intermediate", duration: 307, bpm: 72, key: "E Major", instrumentIds: ["guitar", "piano"] },
  { id: "counting-stars", title: "Counting Stars", artist: "OneRepublic", genre: "Pop", difficulty: "intermediate", duration: 257, bpm: 122, key: "D Minor", instrumentIds: ["piano", "guitar"] },
  { id: "apologize", title: "Apologize", artist: "OneRepublic", genre: "Pop", difficulty: "intermediate", duration: 184, bpm: 136, key: "C Minor", instrumentIds: ["piano"] },
  { id: "roar", title: "Roar", artist: "Katy Perry", genre: "Pop", difficulty: "intermediate", duration: 224, bpm: 90, key: "C Major", instrumentIds: ["piano", "guitar"] },
  { id: "firework", title: "Firework", artist: "Katy Perry", genre: "Pop", difficulty: "intermediate", duration: 227, bpm: 124, key: "Bb Major", instrumentIds: ["piano"] },
  { id: "skyfall", title: "Skyfall", artist: "Adele", genre: "Film", difficulty: "advanced", duration: 284, bpm: 75, key: "B Minor", instrumentIds: ["piano"] },
  { id: "skyfall-bond", title: "Skyfall (James Bond)", artist: "Adele", genre: "Film", difficulty: "advanced", duration: 284, bpm: 75, key: "B Minor", instrumentIds: ["piano", "orchestra"] },
]

/** Most searched / trending artists: from catalog + popular names. Use in Learn & Grow Artists list. */
const EXTRA_TRENDING_ARTIST_NAMES = [
  "Adele", "Ariana Grande", "Beyoncé", "Billie Eilish", "Bob Dylan", "Bruno Mars", "Coldplay",
  "David Bowie", "Drake", "Dua Lipa", "Ed Sheeran", "Elton John", "Fleetwood Mac", "Kendrick Lamar",
  "Michael Jackson", "Pink Floyd", "Prince", "Radiohead", "Stevie Wonder", "Taylor Swift",
]

export const trendingArtists: { name: string; genre?: string }[] = (() => {
  const byName = new Map<string, string>()
  for (const s of songs) {
    if (!byName.has(s.artist)) byName.set(s.artist, s.genre)
  }
  for (const name of EXTRA_TRENDING_ARTIST_NAMES) {
    if (!byName.has(name)) byName.set(name, undefined as unknown as string)
  }
  return Array.from(byName.entries())
    .map(([name, genre]) => ({ name, genre: genre || undefined }))
    .sort((a, b) => a.name.localeCompare(b.name))
})()

export const remixStyles: RemixStyle[] = [
  { id: "jazz", name: "Jazz", color: "#1CB0F6", icon: "Music" },
  { id: "lofi", name: "Lo-Fi", color: "#CE82FF", icon: "Headphones" },
  { id: "orchestral", name: "Orchestral", color: "#FFC800", icon: "Mic2" },
  { id: "edm", name: "EDM", color: "#FF4B4B", icon: "Zap" },
  { id: "reggae", name: "Reggae", color: "#58CC02", icon: "Sun" },
  { id: "bossa-nova", name: "Bossa Nova", color: "#FF9600", icon: "Waves" },
]

/** Pick & Play: 5 distinct instructors (instrument only—no singing). Act like a real personal coach. */
export const instructors: Instructor[] = [
  {
    id: "strict-rick",
    name: "Strict Rick",
    shortDescription: "No-nonsense classical coach",
    color: "#1a1a2e",
    systemPrompt: `You are Strict Rick, the student's personal instrument coach. You're strict, formal, and classical—you care about precision, technique, and discipline. Instrument only, no singing. Talk like a real coach in the room: they can ask you how their session is going, get honest feedback, ask about technique or the piece, or switch pieces. You never sugarcoat; give direct, constructive feedback. If they ask "how am I doing?", give a clear, brief assessment and one concrete tip. Stay in character and be someone they can rely on for straight talk.`,
    liveMessageExamples: [
      "Steady tempo. Don't rush.",
      "Good posture. Breathe.",
      "Focus on the phrase. Again.",
      "Clean articulation on the instrument.",
      "Listen to the silence between notes.",
    ],
  },
  {
    id: "chill-phil",
    name: "Chill Phil",
    shortDescription: "Chill, groove-focused buddy",
    color: "#58CC02",
    systemPrompt: `You are Chill Phil, the student's personal instrument coach and practice buddy. You're relaxed and groove-focused—instrument only, no singing. Talk like a real coach who's right there with them: they can ask how their session is going, get feedback, ask about technique or the piece, or switch songs. You're supportive and casual; you want them to enjoy the process and feel the music. If they ask "how am I doing?", give an encouraging, honest take and maybe one easy tip. Be the coach they can chill and talk to.`,
    liveMessageExamples: [
      "Yeah, feel that groove!",
      "Nice vibe. Keep it loose.",
      "You're in the pocket.",
      "Relax your shoulders. Breathe.",
      "That's the spirit!",
    ],
  },
  {
    id: "warm-norm",
    name: "Warm Norm",
    shortDescription: "Warm, nurturing guide",
    color: "#1CB0F6",
    systemPrompt: `You are Warm Norm, the student's personal instrument coach. You're warm, patient, and nurturing—instrument only, no singing. Talk like a real coach sitting next to them: they can ask how their session is going, get gentle feedback, ask about technique or the piece, or change the piece. You believe in growth at their pace and use kind, affirming language. If they ask "how am I doing?", give a caring assessment and one supportive suggestion. Be the coach they feel safe asking anything.`,
    liveMessageExamples: [
      "You're doing great. Keep going.",
      "I hear improvement. Well done.",
      "Take your time. You've got this.",
      "That was lovely. One more time?",
      "Beautiful tone right there.",
    ],
  },
  {
    id: "witty-kit",
    name: "Witty Kit",
    shortDescription: "Witty, metaphor-loving jazz coach",
    color: "#CE82FF",
    systemPrompt: `You are Witty Kit, the student's personal instrument coach. You're a witty jazz cat—instrument only, no singing. Talk like a real coach with flair: they can ask how their session is going, get feedback, ask about technique or the piece, or switch tunes. You use metaphors, a bit of slang, and dry humor but stay knowledgeable and encouraging. If they ask "how am I doing?", give a memorable, in-character take and one sharp tip. Be the coach that's never boring.`,
    liveMessageExamples: [
      "That's the sauce. Right there.",
      "Listen to the space. It swings.",
      "Cool. Now make it yours.",
      "Nice line. Keep it crisp.",
      "Breathe. The beat waits for no one.",
    ],
  },
  {
    id: "rockin-rob",
    name: "Rockin' Rob",
    shortDescription: "High-energy, punchy motivator",
    color: "#FF4B4B",
    systemPrompt: `You are Rockin' Rob, the student's personal instrument coach. You're high-energy and punchy—instrument only, no singing. Talk like a real coach hyping them up: they can ask how their session is going, get bold feedback, ask about technique or the piece, or change the piece. You motivate with short, clear phrases and real enthusiasm. If they ask "how am I doing?", give an energetic, honest assessment and one punchy tip. Be the coach that makes them want to go again.`,
    liveMessageExamples: [
      "Give it everything!",
      "That's the fire. More!",
      "Lock in. You've got this.",
      "Strong. Now own it.",
      "Yes! That's what I'm talking about.",
    ],
  },
]

/** Base URL for character images — add PNGs to public/characters/ (see public/characters/README.md). */
const characterImage = (id: string) => `/characters/${id}.png`

/** Personalized personas for Juno/Suno remixes — from your character designs. */
export const personas: Persona[] = [
  { id: "veena-vijay", name: "Veena Vijay", shortDescription: "Indian classical", color: "#FF9600", emoji: "🎸", imageUrl: characterImage("veena-vijay") },
  { id: "erhu-eli", name: "Erhu Eli", shortDescription: "Chinese tradition", color: "#FF4B4B", emoji: "🎻", imageUrl: characterImage("erhu-eli") },
  { id: "oud-omar", name: "Oud Omar", shortDescription: "Middle Eastern", color: "#8B7355", emoji: "🪕", imageUrl: characterImage("oud-omar") },
  { id: "shamisen-suki", name: "Shamisen Suki", shortDescription: "Japanese", color: "#CE82FF", emoji: "🎌", imageUrl: characterImage("shamisen-suki") },
  { id: "sitar-samir", name: "Sitar Samir", shortDescription: "North Indian", color: "#1CB0F6", emoji: "🪶", imageUrl: characterImage("sitar-samir") },
  { id: "bodhran-bridget", name: "Bodhràn Bridget", shortDescription: "Irish rhythm", color: "#58CC02", emoji: "🥁", imageUrl: characterImage("bodhran-bridget") },
  { id: "maestro-spirit", name: "Maestro Spirit", shortDescription: "Conductor guide", color: "#1CB0F6", emoji: "👻", imageUrl: characterImage("maestro-spirit") },
  { id: "dj-remix", name: "DJ Remix", shortDescription: "AI remixes & DJ", color: "#CE82FF", emoji: "🎧", imageUrl: characterImage("dj-remix") },
  { id: "cultural-conductor", name: "Cultural Conductor", shortDescription: "World music", color: "#FFC800", emoji: "🎵", imageUrl: characterImage("cultural-conductor") },
  { id: "world-note", name: "World Note", shortDescription: "Global sounds", color: "#58CC02", emoji: "🌍", imageUrl: characterImage("world-note") },
  { id: "ai-firefly", name: "AI Firefly", shortDescription: "AI tutor", color: "#CE82FF", emoji: "✨", imageUrl: characterImage("ai-firefly") },
]

export function generateMockRemixes(personaId?: string): Remix[] {
  return remixStyles.map((style, i) => ({
    id: `remix-${style.id}`,
    style,
    audioUrl: "",
    coverGradient: [
      style.color,
      remixStyles[(i + 1) % remixStyles.length].color,
    ] as [string, string],
    duration: 120 + Math.floor(Math.random() * 120),
    isGenerated: true,
    personaId: personaId ?? undefined,
  }))
}

export function generateMockResult(
  songId: string,
  instrumentId: string,
  personaId?: string,
  songOverride?: { title?: string; artist?: string; genre?: string; key?: string; bpm?: number }
): PerformanceResult {
  const song = songOverride ?? songs.find((s) => s.id === songId)
  const instrument = instruments.find((i) => i.id === instrumentId)

  const score = 70 + Math.floor(Math.random() * 25)
  const stars = score >= 90 ? 5 : score >= 80 ? 4 : score >= 70 ? 3 : 2

  return {
    score,
    xpEarned: Math.floor(score * 1.5),
    stars,
    accuracy: 65 + Math.floor(Math.random() * 30),
    rhythm: 60 + Math.floor(Math.random() * 35),
    timing: 70 + Math.floor(Math.random() * 25),
    technique: {
      rating: stars,
      summary: `Your ${instrument?.name || "instrument"} playing shows promising fundamentals. Your phrasing on "${song?.title || "the song"}" captured the emotional core well, with room to refine dynamics and articulation.`,
      tips: [
        "Focus on maintaining consistent tempo during transitions between sections",
        "Try relaxing your grip to achieve a more natural vibrato",
        "Practice the bridge section slowly to nail the tricky interval jumps",
        "Work on your breathing/bowing consistency for smoother legato passages",
      ],
      strengths: [
        "Strong melodic intuition and note accuracy",
        "Good sense of rhythmic feel in the main theme",
        "Confident attack on the opening phrase",
      ],
    },
    artistInfo: {
      name: song?.artist || "Unknown Artist",
      bio: `${song?.artist || "This artist"} is a legendary figure in ${song?.genre || "music"} whose work has influenced generations of musicians worldwide. Their compositions blend technical mastery with deep emotional expression, creating timeless pieces that continue to resonate with audiences today.`,
      genre: song?.genre || "Various",
      famousSongs: [
        song?.title || "Various works",
        "Additional famous compositions",
        "Other notable pieces",
      ],
      influence: `${song?.artist || "Their"} pioneering approach to ${song?.genre?.toLowerCase() || "music"} revolutionized the genre and set new standards for musical expression. Their influence can be heard in countless modern compositions.`,
    },
    instrumentInfo: {
      name: instrument?.name || "Instrument",
      history: `The ${instrument?.name || "instrument"} has a rich history spanning centuries. Originally developed in ${instrument?.origin || "various regions"}, it has evolved through numerous cultural traditions to become one of the most versatile instruments in the world.`,
      origin: instrument?.origin || "Worldwide",
      famousPlayers: [
        "Legendary virtuoso performers",
        "Contemporary masters",
        "Rising stars in the field",
      ],
      culturalSignificance: `The ${instrument?.name || "instrument"} holds a special place in ${instrument?.origin || "global"} culture, serving as both a solo and ensemble instrument. It plays a central role in traditional ceremonies, modern performances, and everything in between.`,
    },
    songAnalysis: {
      key: song?.key || "C Major",
      tempo: song?.bpm || 120,
      timeSignature: "4/4",
      chordProgression: ["I", "V", "vi", "IV"],
      musicalElements: [
        "Melodic contour with ascending phrases",
        "Harmonic tension and resolution patterns",
        "Dynamic contrast between verses and chorus",
        "Rhythmic motif that recurs throughout",
      ],
      moodDescription: `"${song?.title || "This piece"}" evokes a sense of ${song?.genre === "Jazz" ? "sophistication and improvisation" : song?.genre === "Classical" ? "elegance and emotional depth" : "energy and creative expression"}, with the ${song?.key || "tonal"} foundation providing a ${song?.key?.includes("Minor") ? "melancholic and introspective" : "bright and uplifting"} character.`,
    },
    remixes: generateMockRemixes(personaId),
  }
}

export const encouragingMessages = [
  "Great rhythm!",
  "Nailing it!",
  "Keep that tempo!",
  "Beautiful tone!",
  "You're on fire!",
  "Smooth transition!",
  "Perfect pitch!",
  "Feeling the groove!",
]
